### PR TITLE
Fix module imports and how to access IOBluetooth references

### PR DESCRIPTION
**Pull request by mutesplash**
Tested on 10.15.7 with Python 3.6 and 12.0.1 (in a VM) with Python 3.8.

Without this patch, throws the following errors:
* `macos/discovery.py`: "ImportError: cannot import name 'IOBluetoothDeviceInquiry'"
IOBluetoothDeviceInquiry is not in Foundation, but in IOBluetooth, which it seems a bridge has already been formed for, so I just used that.

* `macos/__init__.py`: "AttributeError: module 'bluetooth' has no attribute 'macos'"
`from . import discovery as discovery` would have also worked.  Not sure why the in-tree import did not work, but this is apparently the correct formation.

Current release does not seem to work with Python 3.6 or 3.9 on High Sierra (10.13.6) as it segfaults (11) even without this patch, probably pyObjC related.

### CODE REVIEW

**Comment by jantman** [comment]
Is this repo maintained? In addition to the issues fixed in this PR, Linux is broken too...

**Comment by hiaselhans** [comment]
hi @mutesplash

sorry i just found this PR now.
Thanks!

I will merge even tough i can not test it now.
I think that older OS versions are not supported due to the github osx sdk...
